#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Apr 01, 2019 04:34:00 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import main_support
from Utils import logger
from Utils import configuration
from Algorithm.main_flow import main as main_regression
from tkinter.filedialog import askopenfilenames, askopenfilename
from tkinter import messagebox
from PIL import ImageTk, Image

config = configuration.config().setup()
log = logger.setup()
#log = logger.add_log_file(log, config)
doc_paths = list()
vec_path = None

STYLE_RANGE = [i for i in range(2, 100)]
DELIMITERS = [r'\n', r'\.', r'[.*?]']
V_PATH = ".\\images\\green_v.png"
X_PATH = ".\\images\\red_x.png"

def start_regression(top, texts_input, vec_input, from_range, to_range, enable_advanced, number_of_words, chunk_size, delay, arch, training, context_window, delimiter):
    # we should check if all the files are exist before running the algorithm
    if (texts_input):
        doc_paths = list(texts_input)

    else:
        messagebox.showerror("Input Error", "You must insert a texts")
        return

    vec_path = vec_input if (vec_input) else None

    config.set("CLUSTER", "from", from_range)
    config.set("CLUSTER", "to", to_range)

    if (enable_advanced):
        config.set("TF-IDF", "num_of_words_per_doc", number_of_words)
        config.set("CHUNKS", "size", chunk_size)
        config.set("CHUNKS", "delay", delay)
        config.set("Word2Vec", "arch", arch)
        config.set("Word2Vec", "training_model", training)
        config.set("Word2Vec", "context_window", context_window)
        config.set("Word2Vec", "text_delimiter", delimiter)

    top.clean_all_steps()

    main = main_regression(config, doc_paths, vec_path)
    try:
        main.run(top)
        messagebox.showinfo("Regression Success", "The process ended successfully!")
    except Exception as e:
        log.error(str(e))
        top.set_x_stage(main.get_stage())
        messagebox.showerror("Regression Error", "Error: " + str(e))



def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    main_support.set_Tk_var()
    top = Toplevel1 (root)
    main_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    main_support.set_Tk_var()
    top = Toplevel1 (w)
    main_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:


    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.num_of_files = 0
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("616x469+388+146")
        top.title("Clustring Text Tool")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.Main_TNotebook = ttk.Notebook(top)
        self.Main_TNotebook.place(relx=0.0, rely=0.0, relheight=0.93, relwidth=0.964)

        self.Main_TNotebook.configure(width=594)
        self.Main_TNotebook.configure(takefocus="")
        self.General_TNotebook = tk.Frame(self.Main_TNotebook)
        self.Main_TNotebook.add(self.General_TNotebook, padding=3)
        self.Main_TNotebook.tab(0, text="General",compound="left",underline="-1",)
        self.General_TNotebook.configure(background="#d9d9d9")
        self.General_TNotebook.configure(highlightbackground="#d9d9d9")
        self.General_TNotebook.configure(highlightcolor="black")
        self.Advanced_Option_TNotebook = tk.Frame(self.Main_TNotebook)
        self.Main_TNotebook.add(self.Advanced_Option_TNotebook, padding=3)
        self.Main_TNotebook.tab(1, text="Advanced Option", compound="none"
                ,underline="-1", )
        self.Advanced_Option_TNotebook.configure(background="#d9d9d9")
        self.Advanced_Option_TNotebook.configure(highlightbackground="#d9d9d9")
        self.Advanced_Option_TNotebook.configure(highlightcolor="black")
        self.Running_TNotebook = tk.Frame(self.Main_TNotebook)
        self.Main_TNotebook.add(self.Running_TNotebook, padding=3)
        self.Main_TNotebook.tab(2, text="Running",compound="left",underline="-1",)
        self.Running_TNotebook.configure(background="#d9d9d9")
        self.Running_TNotebook.configure(highlightbackground="#d9d9d9")
        self.Running_TNotebook.configure(highlightcolor="black")
        self.Statistic_TNotebook = tk.Frame(self.Main_TNotebook)
        self.Main_TNotebook.add(self.Statistic_TNotebook, padding=3)
        self.Main_TNotebook.tab(3, text="Statistics", compound="none", underline="-1"
                ,)
        self.Statistic_TNotebook.configure(background="#d9d9d9")
        self.Statistic_TNotebook.configure(highlightbackground="#d9d9d9")
        self.Statistic_TNotebook.configure(highlightcolor="black")
        self.About_TNotebook = tk.Frame(self.Main_TNotebook)
        self.Main_TNotebook.add(self.About_TNotebook, padding=3)
        self.Main_TNotebook.tab(4, text="About",compound="none",underline="-1",)
        self.About_TNotebook.configure(background="#d9d9d9")
        self.About_TNotebook.configure(highlightbackground="#d9d9d9")
        self.About_TNotebook.configure(highlightcolor="black")

        self.load_text_button = tk.Button(self.General_TNotebook)
        self.load_text_button.place(relx=0.203, rely=0.171, height=24, width=67)
        self.load_text_button.configure(activebackground="#ececec")
        self.load_text_button.configure(activeforeground="#000000")
        self.load_text_button.configure(background="#d9d9d9")
        self.load_text_button.configure(disabledforeground="#a3a3a3")
        self.load_text_button.configure(foreground="#000000")
        self.load_text_button.configure(highlightbackground="#d9d9d9")
        self.load_text_button.configure(highlightcolor="black")
        self.load_text_button.configure(pady="0")
        self.load_text_button.configure(text='''Load Texts''')
        self.load_text_button.configure(command=self.load_text_button_dialog)

        self.texts_entry = tk.Entry(self.General_TNotebook)
        self.texts_entry.place(relx=0.339, rely=0.171,height=20, relwidth=0.278)
        self.texts_entry.configure(background="white")
        self.texts_entry.configure(disabledforeground="#a3a3a3")
        self.texts_entry.configure(font="TkFixedFont")
        self.texts_entry.configure(foreground="#000000")
        self.texts_entry.configure(highlightbackground="#d9d9d9")
        self.texts_entry.configure(highlightcolor="black")
        self.texts_entry.configure(insertbackground="black")
        self.texts_entry.configure(selectbackground="#c4c4c4")
        self.texts_entry.configure(selectforeground="black")

        self.from_spinbox = tk.Spinbox(self.General_TNotebook, from_=5.0, to=100.0)
        self.from_spinbox.place(relx=0.356, rely=0.341, relheight=0.046
                , relwidth=0.076)
        self.from_spinbox.configure(activebackground="#f9f9f9")
        self.from_spinbox.configure(background="white")
        self.from_spinbox.configure(buttonbackground="#d9d9d9")
        self.from_spinbox.configure(disabledforeground="#a3a3a3")
        self.from_spinbox.configure(foreground="black")
        self.from_spinbox.configure(highlightbackground="black")
        self.from_spinbox.configure(highlightcolor="black")
        self.from_spinbox.configure(insertbackground="black")
        self.from_spinbox.configure(selectbackground="#c4c4c4")
        self.from_spinbox.configure(selectforeground="black")
        self.from_spinbox.configure(values=STYLE_RANGE)
        self.from_var = tk.StringVar(root)
        self.from_var.set(config.get("CLUSTER", "from"))
        self.from_spinbox.configure(textvariable=self.from_var)
        self.from_spinbox.configure(command=self.set_from_val)
        self.from_spinbox.configure(state="disable")

        self.to_spinbox = tk.Spinbox(self.General_TNotebook, from_=20.0, to=100.0)
        self.to_spinbox.place(relx=0.492, rely=0.341, relheight=0.046
                , relwidth=0.076)
        self.to_spinbox.configure(activebackground="#f9f9f9")
        self.to_spinbox.configure(background="white")
        self.to_spinbox.configure(buttonbackground="#d9d9d9")
        self.to_spinbox.configure(disabledforeground="#a3a3a3")
        self.to_spinbox.configure(foreground="black")
        self.to_spinbox.configure(highlightbackground="black")
        self.to_spinbox.configure(highlightcolor="black")
        self.to_spinbox.configure(insertbackground="black")
        self.to_spinbox.configure(selectbackground="#c4c4c4")
        self.to_spinbox.configure(selectforeground="black")
        self.to_spinbox.configure(values=STYLE_RANGE)
        self.to_var = tk.StringVar(root)
        self.to_var.set(config.get("CLUSTER", "to"))
        self.to_spinbox.configure(textvariable=self.to_var)
        self.to_spinbox.configure(command=self.set_to_val)
        self.to_spinbox.configure(state="disable")

        self.Style_Range_Label = tk.Label(self.General_TNotebook)
        self.Style_Range_Label.place(relx=0.169, rely=0.341, height=21, width=75)
        self.Style_Range_Label.configure(activebackground="#f9f9f9")
        self.Style_Range_Label.configure(activeforeground="black")
        self.Style_Range_Label.configure(background="#d9d9d9")
        self.Style_Range_Label.configure(disabledforeground="#a3a3a3")
        self.Style_Range_Label.configure(foreground="#000000")
        self.Style_Range_Label.configure(highlightbackground="#d9d9d9")
        self.Style_Range_Label.configure(highlightcolor="black")
        self.Style_Range_Label.configure(text='''Styles Range:''')

        self.Style_Separator_Label = tk.Label(self.General_TNotebook)
        self.Style_Separator_Label.place(relx=0.432, rely=0.317, height=31, width=31)
        self.Style_Separator_Label.configure(activebackground="#f9f9f9")
        self.Style_Separator_Label.configure(activeforeground="black")
        self.Style_Separator_Label.configure(background="#d9d9d9")
        self.Style_Separator_Label.configure(disabledforeground="#a3a3a3")
        self.Style_Separator_Label.configure(foreground="#000000")
        self.Style_Separator_Label.configure(highlightbackground="#d9d9d9")
        self.Style_Separator_Label.configure(highlightcolor="black")
        self.Style_Separator_Label.configure(text='''-''')

        self.load_vec_button = tk.Button(self.General_TNotebook)
        self.load_vec_button.place(relx=0.22, rely=0.78, height=24, width=59)
        self.load_vec_button.configure(activebackground="#ececec")
        self.load_vec_button.configure(activeforeground="#000000")
        self.load_vec_button.configure(background="#d9d9d9")
        self.load_vec_button.configure(disabledforeground="#a3a3a3")
        self.load_vec_button.configure(foreground="#000000")
        self.load_vec_button.configure(highlightbackground="#d9d9d9")
        self.load_vec_button.configure(highlightcolor="black")
        self.load_vec_button.configure(pady="0")
        self.load_vec_button.configure(state='disabled')
        self.load_vec_button.configure(text='''Load Vec''')
        self.load_vec_button.configure(command=self.load_vec_button_dialog)

        self.add_word_emedding_Cbutton3 = tk.Checkbutton(self.General_TNotebook)
        self.add_word_emedding_Cbutton3.place(relx=0.136, rely=0.634, relheight=0.061
                , relwidth=0.236)
        self.add_word_emedding_Cbutton3.configure(activebackground="#ececec")
        self.add_word_emedding_Cbutton3.configure(activeforeground="#000000")
        self.add_word_emedding_Cbutton3.configure(background="#d9d9d9")
        self.add_word_emedding_Cbutton3.configure(disabledforeground="#a3a3a3")
        self.add_word_emedding_Cbutton3.configure(foreground="#000000")
        self.add_word_emedding_Cbutton3.configure(highlightbackground="#d9d9d9")
        self.add_word_emedding_Cbutton3.configure(highlightcolor="black")
        self.add_word_emedding_Cbutton3.configure(justify='left')
        self.add_word_emedding_Cbutton3.configure(text='''Add Word Emedding''')
        self.add_word_emedding_Cbutton_var = tk.IntVar()
        self.add_word_emedding_Cbutton3.configure(variable=self.add_word_emedding_Cbutton_var)
        self.add_word_emedding_Cbutton3.configure(command=self.add_word_embedding_checkbox)
        self.add_word_emedding_Cbutton3.deselect()



        self.vec_entry = tk.Entry(self.General_TNotebook)
        self.vec_entry.place(relx=0.356, rely=0.78,height=20, relwidth=0.278)
        self.vec_entry.configure(background="white")
        self.vec_entry.configure(disabledforeground="#a3a3a3")
        self.vec_entry.configure(font="TkFixedFont")
        self.vec_entry.configure(foreground="#000000")
        self.vec_entry.configure(highlightbackground="#d9d9d9")
        self.vec_entry.configure(highlightcolor="black")
        self.vec_entry.configure(insertbackground="black")
        self.vec_entry.configure(selectbackground="#c4c4c4")
        self.vec_entry.configure(selectforeground="black")
        self.vec_entry.configure(state='disabled')

        self.TSeparator2 = ttk.Separator(self.General_TNotebook)
        self.TSeparator2.place(relx=0.085, rely=0.537, relwidth=0.847)

        self.Enable_Cbutton = tk.Checkbutton(self.Advanced_Option_TNotebook)
        self.Enable_Cbutton.place(relx=0.051, rely=0.014, relheight=0.061
                , relwidth=0.107)
        self.Enable_Cbutton.configure(activebackground="#ececec")
        self.Enable_Cbutton.configure(activeforeground="#000000")
        self.Enable_Cbutton.configure(background="#d9d9d9")
        self.Enable_Cbutton.configure(disabledforeground="#a3a3a3")
        self.Enable_Cbutton.configure(foreground="#000000")
        self.Enable_Cbutton.configure(highlightbackground="#d9d9d9")
        self.Enable_Cbutton.configure(highlightcolor="black")
        self.Enable_Cbutton.configure(justify='left')
        self.Enable_Cbutton.configure(text='''Enable''')
        self.Enable_Cbutton_var = tk.IntVar()
        self.Enable_Cbutton.configure(variable=self.Enable_Cbutton_var)
        self.Enable_Cbutton.configure(command=self.enable_button_handler)
        self.Enable_Cbutton.deselect()

        self.Word2Vec_Labelframe = tk.LabelFrame(self.Advanced_Option_TNotebook)
        self.Word2Vec_Labelframe.place(relx=0.068, rely=0.500, relheight=0.478
                , relwidth=0.898)
        self.Word2Vec_Labelframe.configure(relief='groove')
        self.Word2Vec_Labelframe.configure(foreground="black")
        self.Word2Vec_Labelframe.configure(text='''Word2Vec''')
        self.Word2Vec_Labelframe.configure(background="#d9d9d9")
        self.Word2Vec_Labelframe.configure(highlightbackground="#d9d9d9")
        self.Word2Vec_Labelframe.configure(highlightcolor="black")
        self.Word2Vec_Labelframe.configure(width=400)

        self.arch_var = tk.StringVar()

        self.Skip_Gram_Radiobutton = tk.Radiobutton(self.Word2Vec_Labelframe)
        self.Skip_Gram_Radiobutton.place(relx=0.400, rely=0.140, relheight=0.161
                , relwidth=0.155, bordermode='ignore')
        self.Skip_Gram_Radiobutton.configure(activebackground="#ececec")
        self.Skip_Gram_Radiobutton.configure(activeforeground="#000000")
        self.Skip_Gram_Radiobutton.configure(background="#d9d9d9")
        self.Skip_Gram_Radiobutton.configure(disabledforeground="#a3a3a3")
        self.Skip_Gram_Radiobutton.configure(foreground="#000000")
        self.Skip_Gram_Radiobutton.configure(highlightbackground="#d9d9d9")
        self.Skip_Gram_Radiobutton.configure(highlightcolor="black")
        self.Skip_Gram_Radiobutton.configure(justify='left')
        self.Skip_Gram_Radiobutton.configure(state='disabled')
        self.Skip_Gram_Radiobutton.configure(text='''Skip Gram''')
        self.Skip_Gram_Radiobutton.configure(variable=self.arch_var)
        self.Skip_Gram_Radiobutton.configure(value="Skip-Gram")


        self.CBOW_Radiobutton = tk.Radiobutton(self.Word2Vec_Labelframe)
        self.CBOW_Radiobutton.place(relx=0.600, rely=0.140, relheight=0.161
                , relwidth=0.119, bordermode='ignore')
        self.CBOW_Radiobutton.configure(activebackground="#ececec")
        self.CBOW_Radiobutton.configure(activeforeground="#000000")
        self.CBOW_Radiobutton.configure(background="#d9d9d9")
        self.CBOW_Radiobutton.configure(disabledforeground="#a3a3a3")
        self.CBOW_Radiobutton.configure(foreground="#000000")
        self.CBOW_Radiobutton.configure(highlightbackground="#d9d9d9")
        self.CBOW_Radiobutton.configure(highlightcolor="black")
        self.CBOW_Radiobutton.configure(justify='left')
        self.CBOW_Radiobutton.configure(state='disabled')
        self.CBOW_Radiobutton.configure(text='''CBOW''')
        self.CBOW_Radiobutton.configure(variable=self.arch_var)
        self.CBOW_Radiobutton.configure(value="CBOW")

        self.arch_var.set(config.get("Word2Vec", "arch"))
        self.training_var = tk.StringVar()

        self.Softmax_Radiobutton = tk.Radiobutton(self.Word2Vec_Labelframe)
        self.Softmax_Radiobutton.place(relx=0.400, rely=0.335, relheight=0.161
                , relwidth=0.134, bordermode='ignore')
        self.Softmax_Radiobutton.configure(activebackground="#ececec")
        self.Softmax_Radiobutton.configure(activeforeground="#000000")
        self.Softmax_Radiobutton.configure(background="#d9d9d9")
        self.Softmax_Radiobutton.configure(disabledforeground="#a3a3a3")
        self.Softmax_Radiobutton.configure(foreground="#000000")
        self.Softmax_Radiobutton.configure(highlightbackground="#d9d9d9")
        self.Softmax_Radiobutton.configure(highlightcolor="black")
        self.Softmax_Radiobutton.configure(justify='left')
        self.Softmax_Radiobutton.configure(state='disabled')
        self.Softmax_Radiobutton.configure(text='''Softmax''')
        self.Softmax_Radiobutton.configure(variable=self.training_var)
        self.Softmax_Radiobutton.configure(value="Softmax")

        self.Negative_Sampling_Radiobutton = tk.Radiobutton(self.Word2Vec_Labelframe)
        self.Negative_Sampling_Radiobutton.place(relx=0.600, rely=0.335, relheight=0.161
                , relwidth=0.242, bordermode='ignore')
        self.Negative_Sampling_Radiobutton.configure(activebackground="#ececec")
        self.Negative_Sampling_Radiobutton.configure(activeforeground="#000000")
        self.Negative_Sampling_Radiobutton.configure(background="#d9d9d9")
        self.Negative_Sampling_Radiobutton.configure(disabledforeground="#a3a3a3")
        self.Negative_Sampling_Radiobutton.configure(foreground="#000000")
        self.Negative_Sampling_Radiobutton.configure(highlightbackground="#d9d9d9")
        self.Negative_Sampling_Radiobutton.configure(highlightcolor="black")
        self.Negative_Sampling_Radiobutton.configure(justify='left')
        self.Negative_Sampling_Radiobutton.configure(state='disabled')
        self.Negative_Sampling_Radiobutton.configure(text='''Negative Sampling''')
        self.Negative_Sampling_Radiobutton.configure(variable=self.training_var)
        self.Negative_Sampling_Radiobutton.configure(value="Negative_Sampling")

        self.training_var.set(config.get("Word2Vec", "training_model"))

        self.Architecture_Label = tk.Label(self.Word2Vec_Labelframe)
        self.Architecture_Label.place(relx=0.21, rely=0.150, height=21, width=74
                , bordermode='ignore')
        self.Architecture_Label.configure(activebackground="#f9f9f9")
        self.Architecture_Label.configure(activeforeground="black")
        self.Architecture_Label.configure(background="#d9d9d9")
        self.Architecture_Label.configure(disabledforeground="#a3a3a3")
        self.Architecture_Label.configure(foreground="#000000")
        self.Architecture_Label.configure(highlightbackground="#d9d9d9")
        self.Architecture_Label.configure(highlightcolor="black")
        self.Architecture_Label.configure(text='''Architecture:''')

        self.Model_Label = tk.Label(self.Word2Vec_Labelframe)
        self.Model_Label.place(relx=0.270, rely=0.350, height=21, width=43
                , bordermode='ignore')
        self.Model_Label.configure(activebackground="#f9f9f9")
        self.Model_Label.configure(activeforeground="black")
        self.Model_Label.configure(background="#d9d9d9")
        self.Model_Label.configure(disabledforeground="#a3a3a3")
        self.Model_Label.configure(foreground="#000000")
        self.Model_Label.configure(highlightbackground="#d9d9d9")
        self.Model_Label.configure(highlightcolor="black")
        self.Model_Label.configure(text='''Model:''')

        self.Context_Windows_Label = tk.Label(self.Word2Vec_Labelframe)
        self.Context_Windows_Label.place(relx=0.155, rely=0.580, height=21, width=102
                , bordermode='ignore')
        self.Context_Windows_Label.configure(activebackground="#f9f9f9")
        self.Context_Windows_Label.configure(activeforeground="black")
        self.Context_Windows_Label.configure(background="#d9d9d9")
        self.Context_Windows_Label.configure(disabledforeground="#a3a3a3")
        self.Context_Windows_Label.configure(foreground="#000000")
        self.Context_Windows_Label.configure(highlightbackground="#d9d9d9")
        self.Context_Windows_Label.configure(highlightcolor="black")
        self.Context_Windows_Label.configure(text='''Context Windows:''')

        self.Delimiter_Label = tk.Label(self.Word2Vec_Labelframe)
        self.Delimiter_Label.place(relx=0.197, rely=0.8, height=21, width=102
                                         , bordermode='ignore')
        self.Delimiter_Label.configure(activebackground="#f9f9f9")
        self.Delimiter_Label.configure(activeforeground="black")
        self.Delimiter_Label.configure(background="#d9d9d9")
        self.Delimiter_Label.configure(disabledforeground="#a3a3a3")
        self.Delimiter_Label.configure(foreground="#000000")
        self.Delimiter_Label.configure(highlightbackground="#d9d9d9")
        self.Delimiter_Label.configure(highlightcolor="black")
        self.Delimiter_Label.configure(text='''Delimiter:''')


        self.Context_Windows_Spinbox = tk.Spinbox(self.Word2Vec_Labelframe, from_=1.0, to=100.0)
        self.Context_Windows_Spinbox.place(relx=0.396, rely=0.580, relheight=0.100, relwidth=0.16
                , bordermode='ignore')
        self.Context_Windows_Spinbox.configure(activebackground="#f9f9f9")
        self.Context_Windows_Spinbox.configure(background="white")
        self.Context_Windows_Spinbox.configure(buttonbackground="#d9d9d9")
        self.Context_Windows_Spinbox.configure(disabledforeground="#a3a3a3")
        self.Context_Windows_Spinbox.configure(foreground="black")
        self.Context_Windows_Spinbox.configure(highlightbackground="black")
        self.Context_Windows_Spinbox.configure(highlightcolor="black")
        self.Context_Windows_Spinbox.configure(insertbackground="black")
        self.Context_Windows_Spinbox.configure(selectbackground="#c4c4c4")
        self.Context_Windows_Spinbox.configure(selectforeground="black")
        self.Context_Windows_Spinbox.configure(state='disabled')
        self.Context_Windows_var = tk.StringVar(root)
        self.Context_Windows_var.set(config.get("Word2Vec", "context_window"))
        self.Context_Windows_Spinbox.configure(textvariable=self.Context_Windows_var)

        self.Delimiter_var = tk.StringVar(root)
        self.Delimiter_var.set(DELIMITERS[0])  # default value
        self.Delimiter_window = tk.OptionMenu(self.Word2Vec_Labelframe, self.Delimiter_var, *DELIMITERS)
        self.Delimiter_window.place(relx=0.392, rely=0.8, height=20, relwidth=0.17)
        self.Delimiter_window.configure(background="white")
        self.Delimiter_window.configure(disabledforeground="#a3a3a3")
        self.Delimiter_window.configure(font="TkFixedFont")
        self.Delimiter_window.configure(foreground="#000000")
        self.Delimiter_window.configure(highlightbackground="#d9d9d9")
        self.Delimiter_window.configure(highlightcolor="black")
        self.Delimiter_window.configure(state='disabled')

        self.Chunks_Labelframe = tk.LabelFrame(self.Advanced_Option_TNotebook)
        self.Chunks_Labelframe.place(relx=0.068, rely=0.240, relheight=0.255
                , relwidth=0.898)
        self.Chunks_Labelframe.configure(relief='groove')
        self.Chunks_Labelframe.configure(foreground="black")
        self.Chunks_Labelframe.configure(text='''Chunks''')
        self.Chunks_Labelframe.configure(background="#d9d9d9")
        self.Chunks_Labelframe.configure(highlightbackground="#d9d9d9")
        self.Chunks_Labelframe.configure(highlightcolor="black")
        self.Chunks_Labelframe.configure(width=530)

        self.Chunk_Size_Spinbox = tk.Spinbox(self.Chunks_Labelframe, from_=1.0, to=100.0)
        self.Chunk_Size_Spinbox.place(relx=0.396, rely=0.24, relheight=0.200, relwidth=0.16
                , bordermode='ignore')
        self.Chunk_Size_Spinbox.configure(activebackground="#f9f9f9")
        self.Chunk_Size_Spinbox.configure(background="white")
        self.Chunk_Size_Spinbox.configure(buttonbackground="#d9d9d9")
        self.Chunk_Size_Spinbox.configure(disabledforeground="#a3a3a3")
        self.Chunk_Size_Spinbox.configure(foreground="black")
        self.Chunk_Size_Spinbox.configure(highlightbackground="black")
        self.Chunk_Size_Spinbox.configure(highlightcolor="black")
        self.Chunk_Size_Spinbox.configure(insertbackground="black")
        self.Chunk_Size_Spinbox.configure(selectbackground="#c4c4c4")
        self.Chunk_Size_Spinbox.configure(selectforeground="black")
        self.Chunk_Size_Spinbox.configure(state='disabled')
        self.Chunk_Size_var = tk.StringVar(root)
        self.Chunk_Size_var.set(config.get("CHUNKS", "size"))
        self.Chunk_Size_Spinbox.configure(textvariable=self.Chunk_Size_var)
        self.Chunk_Size_Spinbox.configure(command=self.set_chunk_size_val)

        self.Delay_Spinbox = tk.Spinbox(self.Chunks_Labelframe, from_=1.0, to=100.0)
        self.Delay_Spinbox.place(relx=0.396, rely=0.56, relheight=0.200, relwidth=0.16
                , bordermode='ignore')
        self.Delay_Spinbox.configure(activebackground="#f9f9f9")
        self.Delay_Spinbox.configure(background="white")
        self.Delay_Spinbox.configure(buttonbackground="#d9d9d9")
        self.Delay_Spinbox.configure(disabledforeground="#a3a3a3")
        self.Delay_Spinbox.configure(foreground="black")
        self.Delay_Spinbox.configure(highlightbackground="black")
        self.Delay_Spinbox.configure(highlightcolor="black")
        self.Delay_Spinbox.configure(insertbackground="black")
        self.Delay_Spinbox.configure(selectbackground="#c4c4c4")
        self.Delay_Spinbox.configure(selectforeground="black")
        self.Delay_Spinbox.configure(state='disabled')
        self.Delay_var = tk.StringVar(root)
        self.Delay_var.set(config.get("CHUNKS", "delay"))
        self.Delay_Spinbox.configure(textvariable=self.Delay_var)
        self.Delay_Spinbox.configure(command=self.set_delay_val)

        self.Chunk_Size_Label = tk.Label(self.Chunks_Labelframe)
        self.Chunk_Size_Label.place(relx=0.225, rely=0.24, height=21, width=67
                , bordermode='ignore')
        self.Chunk_Size_Label.configure(activebackground="#f9f9f9")
        self.Chunk_Size_Label.configure(activeforeground="black")
        self.Chunk_Size_Label.configure(background="#d9d9d9")
        self.Chunk_Size_Label.configure(disabledforeground="#a3a3a3")
        self.Chunk_Size_Label.configure(foreground="#000000")
        self.Chunk_Size_Label.configure(highlightbackground="#d9d9d9")
        self.Chunk_Size_Label.configure(highlightcolor="black")
        self.Chunk_Size_Label.configure(text='''Chunk Size:''')

        self.Delay_Label = tk.Label(self.Chunks_Labelframe)
        self.Delay_Label.place(relx=0.172, rely=0.56, height=21, width=95
                , bordermode='ignore')
        self.Delay_Label.configure(activebackground="#f9f9f9")
        self.Delay_Label.configure(activeforeground="black")
        self.Delay_Label.configure(background="#d9d9d9")
        self.Delay_Label.configure(disabledforeground="#a3a3a3")
        self.Delay_Label.configure(foreground="#000000")
        self.Delay_Label.configure(highlightbackground="#d9d9d9")
        self.Delay_Label.configure(highlightcolor="black")
        self.Delay_Label.configure(text='''Delay Parameter:''')

        self.TFIDF_Labelframe = tk.LabelFrame(self.Advanced_Option_TNotebook)
        self.TFIDF_Labelframe.place(relx=0.068, rely=0.078, relheight=0.159
                , relwidth=0.898)
        self.TFIDF_Labelframe.configure(relief='groove')
        self.TFIDF_Labelframe.configure(foreground="black")
        self.TFIDF_Labelframe.configure(text='''TF-IDF''')
        self.TFIDF_Labelframe.configure(background="#d9d9d9")
        self.TFIDF_Labelframe.configure(highlightbackground="#d9d9d9")
        self.TFIDF_Labelframe.configure(highlightcolor="black")
        self.TFIDF_Labelframe.configure(width=150)

        self.Number_Of_Words_Label = tk.Label(self.TFIDF_Labelframe)
        self.Number_Of_Words_Label.place(relx=0.019, rely=0.462, height=21, width=176
                , bordermode='ignore')
        self.Number_Of_Words_Label.configure(activebackground="#f9f9f9")
        self.Number_Of_Words_Label.configure(activeforeground="black")
        self.Number_Of_Words_Label.configure(background="#d9d9d9")
        self.Number_Of_Words_Label.configure(disabledforeground="#a3a3a3")
        self.Number_Of_Words_Label.configure(foreground="#000000")
        self.Number_Of_Words_Label.configure(highlightbackground="#d9d9d9")
        self.Number_Of_Words_Label.configure(highlightcolor="black")
        self.Number_Of_Words_Label.configure(text='''Number of Words in Document:''')

        self.Number_Of_Words_Spinbox = tk.Spinbox(self.TFIDF_Labelframe, from_=1.0, to=100.0)
        self.Number_Of_Words_Spinbox.place(relx=0.396, rely=0.462, relheight=0.400
                , relwidth=0.16, bordermode='ignore')
        self.Number_Of_Words_Spinbox.configure(activebackground="#f9f9f9")
        self.Number_Of_Words_Spinbox.configure(background="white")
        self.Number_Of_Words_Spinbox.configure(buttonbackground="#d9d9d9")
        self.Number_Of_Words_Spinbox.configure(disabledforeground="#a3a3a3")
        self.Number_Of_Words_Spinbox.configure(foreground="black")
        self.Number_Of_Words_Spinbox.configure(highlightbackground="black")
        self.Number_Of_Words_Spinbox.configure(highlightcolor="black")
        self.Number_Of_Words_Spinbox.configure(insertbackground="black")
        self.Number_Of_Words_Spinbox.configure(selectbackground="#c4c4c4")
        self.Number_Of_Words_Spinbox.configure(selectforeground="black")
        self.Number_Of_Words_Spinbox.configure(state='disabled')
        self.Number_Of_Words_var = tk.StringVar(root)
        self.Number_Of_Words_var.set(config.get("TF-IDF", "num_of_words_per_doc"))
        self.Number_Of_Words_Spinbox.configure(textvariable=self.Number_Of_Words_var)
        self.Number_Of_Words_Spinbox.configure(command=self.set_number_of_words_val)


        self.run_button = tk.Button(self.Running_TNotebook)
        self.run_button.place(relx=0.458, rely=0.073, height=24, width=38)
        self.run_button.configure(activebackground="#ececec")
        self.run_button.configure(activeforeground="#000000")
        self.run_button.configure(background="#d9d9d9")
        self.run_button.configure(disabledforeground="#a3a3a3")
        self.run_button.configure(foreground="#000000")
        self.run_button.configure(highlightbackground="#d9d9d9")
        self.run_button.configure(highlightcolor="black")
        self.run_button.configure(pady="0")
        self.run_button.configure(text='''RUN!''')
        self.run_button.configure(command=lambda : start_regression(self, self.doc_paths, self.vec_entry.get(),
                                                                    self.from_var.get(),
                                                                    self.to_var.get(),
                                                                    self.Enable_Cbutton_var.get(),
                                                                    self.Number_Of_Words_var.get(),
                                                                    self.Chunk_Size_var.get(),
                                                                    self.Delay_var.get(),
                                                                    self.arch_var.get(),
                                                                    self.training_var.get(),
                                                                    self.Context_Windows_var.get(),
                                                                    self.Delimiter_var.get()))

        self.Processing_Labelframe = tk.LabelFrame(self.Running_TNotebook)
        self.Processing_Labelframe.place(relx=0.051, rely=0.146, relheight=0.768
                , relwidth=0.898)
        self.Processing_Labelframe.configure(relief='groove')
        self.Processing_Labelframe.configure(foreground="black")
        self.Processing_Labelframe.configure(labelanchor="n")
        self.Processing_Labelframe.configure(text='''Processing''')
        self.Processing_Labelframe.configure(background="#d9d9d9")
        self.Processing_Labelframe.configure(highlightbackground="#d9d9d9")
        self.Processing_Labelframe.configure(highlightcolor="black")
        self.Processing_Labelframe.configure(width=530)

        self.v_img_get_texts = ImageTk.PhotoImage(Image.open(V_PATH).resize((10, 10), Image.ANTIALIAS))
        self.v_get_texts_label = tk.Label(self.Processing_Labelframe, image=self.v_img_get_texts, background="#d9d9d9")

        self.x_img_get_texts = ImageTk.PhotoImage(Image.open(X_PATH).resize((10, 10), Image.ANTIALIAS))
        self.x_get_texts_label = tk.Label(self.Processing_Labelframe, image=self.x_img_get_texts, background="#d9d9d9")

        self.Get_Texts_proc_label = tk.Label(self.Processing_Labelframe)
        self.Get_Texts_proc_label.place(relx=0.06, rely=0.0)
        self.Get_Texts_proc_label.configure(activebackground="#f9f9f9")
        self.Get_Texts_proc_label.configure(activeforeground="black")
        self.Get_Texts_proc_label.configure(background="#d9d9d9")
        self.Get_Texts_proc_label.configure(disabledforeground="#a3a3a3")
        self.Get_Texts_proc_label.configure(foreground="#000000")
        self.Get_Texts_proc_label.configure(highlightbackground="#d9d9d9")
        self.Get_Texts_proc_label.configure(highlightcolor="black")
        self.Get_Texts_proc_label.configure(text='''Get Texts''')

        self.v_img_word2vec = ImageTk.PhotoImage(Image.open(V_PATH).resize((10, 10), Image.ANTIALIAS))
        self.v_word2vec_label = tk.Label(self.Processing_Labelframe, image=self.v_img_word2vec, background="#d9d9d9")

        self.x_img_word2vec = ImageTk.PhotoImage(Image.open(X_PATH).resize((10, 10), Image.ANTIALIAS))
        self.x_word2vec_label = tk.Label(self.Processing_Labelframe, image=self.x_img_word2vec, background="#d9d9d9")

        self.Word2Vec_proc_label = tk.Label(self.Processing_Labelframe)
        self.Word2Vec_proc_label.place(relx=0.06, rely=0.11)
        self.Word2Vec_proc_label.configure(activebackground="#f9f9f9")
        self.Word2Vec_proc_label.configure(activeforeground="black")
        self.Word2Vec_proc_label.configure(background="#d9d9d9")
        self.Word2Vec_proc_label.configure(disabledforeground="#a3a3a3")
        self.Word2Vec_proc_label.configure(foreground="#000000")
        self.Word2Vec_proc_label.configure(highlightbackground="#d9d9d9")
        self.Word2Vec_proc_label.configure(highlightcolor="black")
        self.Word2Vec_proc_label.configure(text='''Word2Vec''')

        self.v_img_building_chunks = ImageTk.PhotoImage(Image.open(V_PATH).resize((10, 10), Image.ANTIALIAS))
        self.v_building_chunks_label = tk.Label(self.Processing_Labelframe, image=self.v_img_building_chunks, background="#d9d9d9")

        self.x_img_building_chunks = ImageTk.PhotoImage(Image.open(X_PATH).resize((10, 10), Image.ANTIALIAS))
        self.x_building_chunks_label = tk.Label(self.Processing_Labelframe, image=self.x_img_building_chunks, background="#d9d9d9")

        self.Building_Chunks_proc_label = tk.Label(self.Processing_Labelframe)
        self.Building_Chunks_proc_label.place(relx=0.06, rely=0.22)
        self.Building_Chunks_proc_label.configure(activebackground="#f9f9f9")
        self.Building_Chunks_proc_label.configure(activeforeground="black")
        self.Building_Chunks_proc_label.configure(background="#d9d9d9")
        self.Building_Chunks_proc_label.configure(disabledforeground="#a3a3a3")
        self.Building_Chunks_proc_label.configure(foreground="#000000")
        self.Building_Chunks_proc_label.configure(highlightbackground="#d9d9d9")
        self.Building_Chunks_proc_label.configure(highlightcolor="black")
        self.Building_Chunks_proc_label.configure(text='''Building Chunks''')

        self.v_img_metric = ImageTk.PhotoImage(Image.open(V_PATH).resize((10, 10), Image.ANTIALIAS))
        self.v_metric_label = tk.Label(self.Processing_Labelframe, image=self.v_img_metric, background="#d9d9d9")

        self.x_img_metric = ImageTk.PhotoImage(Image.open(X_PATH).resize((10, 10), Image.ANTIALIAS))
        self.x_metric_label = tk.Label(self.Processing_Labelframe, image=self.x_img_metric, background="#d9d9d9")

        self.Metric_proc_label = tk.Label(self.Processing_Labelframe)
        self.Metric_proc_label.place(relx=0.06, rely=0.33)
        self.Metric_proc_label.configure(activebackground="#f9f9f9")
        self.Metric_proc_label.configure(activeforeground="black")
        self.Metric_proc_label.configure(background="#d9d9d9")
        self.Metric_proc_label.configure(disabledforeground="#a3a3a3")
        self.Metric_proc_label.configure(foreground="#000000")
        self.Metric_proc_label.configure(highlightbackground="#d9d9d9")
        self.Metric_proc_label.configure(highlightcolor="black")
        self.Metric_proc_label.configure(text='''Create Distance Matrix''')

        self.v_img_pam = ImageTk.PhotoImage(Image.open(V_PATH).resize((10, 10), Image.ANTIALIAS))
        self.v_pam_label = tk.Label(self.Processing_Labelframe, image=self.v_img_pam, background="#d9d9d9")

        self.x_img_pam = ImageTk.PhotoImage(Image.open(X_PATH).resize((10, 10), Image.ANTIALIAS))
        self.x_pam_label = tk.Label(self.Processing_Labelframe, image=self.x_img_pam, background="#d9d9d9")

        self.PAM_proc_label = tk.Label(self.Processing_Labelframe)
        self.PAM_proc_label.place(relx=0.06, rely=0.44)
        self.PAM_proc_label.configure(activebackground="#f9f9f9")
        self.PAM_proc_label.configure(activeforeground="black")
        self.PAM_proc_label.configure(background="#d9d9d9")
        self.PAM_proc_label.configure(disabledforeground="#a3a3a3")
        self.PAM_proc_label.configure(foreground="#000000")
        self.PAM_proc_label.configure(highlightbackground="#d9d9d9")
        self.PAM_proc_label.configure(highlightcolor="black")
        self.PAM_proc_label.configure(text='''PAM''')

        self.v_img_silhouette = ImageTk.PhotoImage(Image.open(V_PATH).resize((10, 10), Image.ANTIALIAS))
        self.v_silhouette_label = tk.Label(self.Processing_Labelframe, image=self.v_img_silhouette, background="#d9d9d9")

        self.x_img_silhouette = ImageTk.PhotoImage(Image.open(X_PATH).resize((10, 10), Image.ANTIALIAS))
        self.x_silhouette_label = tk.Label(self.Processing_Labelframe, image=self.x_img_silhouette, background="#d9d9d9")

        self.Silhouette_proc_label = tk.Label(self.Processing_Labelframe)
        self.Silhouette_proc_label.place(relx=0.06, rely=0.55)
        self.Silhouette_proc_label.configure(activebackground="#f9f9f9")
        self.Silhouette_proc_label.configure(activeforeground="black")
        self.Silhouette_proc_label.configure(background="#d9d9d9")
        self.Silhouette_proc_label.configure(disabledforeground="#a3a3a3")
        self.Silhouette_proc_label.configure(foreground="#000000")
        self.Silhouette_proc_label.configure(highlightbackground="#d9d9d9")
        self.Silhouette_proc_label.configure(highlightcolor="black")
        self.Silhouette_proc_label.configure(text='''Silhouette''')


        self.Processing_TProgressbar = ttk.Progressbar(self.Processing_Labelframe)
        self.Processing_TProgressbar.place(relx=0.057, rely=0.857, relwidth=0.868
                , relheight=0.0, height=22, bordermode='ignore')
        self.Processing_TProgressbar.configure(mode="determinate")
        self.Processing_TProgressbar['value'] = 0

        self.TCombobox1 = ttk.Combobox(self.Statistic_TNotebook)
        self.TCombobox1.place(relx=0.237, rely=0.098, relheight=0.051
                , relwidth=0.242)
        self.value_list = ["Documents Clustring", "Clustrs Map", "Interior Clustring",]
        self.TCombobox1.configure(values=self.value_list)
        self.TCombobox1.configure(textvariable=main_support.combobox)
        self.TCombobox1.configure(foreground="#000000")

        self.Select_Graph_Label = tk.Label(self.Statistic_TNotebook)
        self.Select_Graph_Label.place(relx=0.076, rely=0.098, height=21, width=75)
        self.Select_Graph_Label.configure(activebackground="#f9f9f9")
        self.Select_Graph_Label.configure(activeforeground="black")
        self.Select_Graph_Label.configure(background="#d9d9d9")
        self.Select_Graph_Label.configure(disabledforeground="#a3a3a3")
        self.Select_Graph_Label.configure(foreground="#000000")
        self.Select_Graph_Label.configure(highlightbackground="#d9d9d9")
        self.Select_Graph_Label.configure(highlightcolor="black")
        self.Select_Graph_Label.configure(text='''Select Graph:''')

        self.Graph_Canvas = tk.Canvas(self.Statistic_TNotebook)
        self.Graph_Canvas.place(relx=0.068, rely=0.317, relheight=0.641
                , relwidth=0.886)
        self.Graph_Canvas.configure(background="#d9d9d9")
        self.Graph_Canvas.configure(borderwidth="2")
        self.Graph_Canvas.configure(highlightbackground="#d9d9d9")
        self.Graph_Canvas.configure(highlightcolor="black")
        self.Graph_Canvas.configure(insertbackground="black")
        self.Graph_Canvas.configure(relief='ridge')
        self.Graph_Canvas.configure(selectbackground="#c4c4c4")
        self.Graph_Canvas.configure(selectforeground="black")
        self.Graph_Canvas.configure(width=523)

        self.TCombobox2 = ttk.Combobox(self.Statistic_TNotebook)
        self.TCombobox2.place(relx=0.237, rely=0.171, relheight=0.051
                , relwidth=0.242)
        self.TCombobox2.configure(textvariable=main_support.combobox)
        self.TCombobox2.configure(takefocus="")

        self.Select_Doc_Label = tk.Label(self.Statistic_TNotebook)
        self.Select_Doc_Label.place(relx=0.034, rely=0.171, height=21, width=105)
        self.Select_Doc_Label.configure(activebackground="#f9f9f9")
        self.Select_Doc_Label.configure(activeforeground="black")
        self.Select_Doc_Label.configure(background="#d9d9d9")
        self.Select_Doc_Label.configure(disabledforeground="#a3a3a3")
        self.Select_Doc_Label.configure(foreground="#000000")
        self.Select_Doc_Label.configure(highlightbackground="#d9d9d9")
        self.Select_Doc_Label.configure(highlightcolor="black")
        self.Select_Doc_Label.configure(text='''Select Document:''')

        self.Result_Labelframe = tk.LabelFrame(self.Statistic_TNotebook)
        self.Result_Labelframe.place(relx=0.542, rely=0.024, relheight=0.232
                , relwidth=0.407)
        self.Result_Labelframe.configure(relief='groove')
        self.Result_Labelframe.configure(foreground="black")
        self.Result_Labelframe.configure(labelanchor="n")
        self.Result_Labelframe.configure(text='''Result''')
        self.Result_Labelframe.configure(background="#d9d9d9")
        self.Result_Labelframe.configure(highlightbackground="#d9d9d9")
        self.Result_Labelframe.configure(highlightcolor="black")
        self.Result_Labelframe.configure(width=240)

        self.Number_Of_Style_Label = tk.Label(self.Result_Labelframe)
        self.Number_Of_Style_Label.place(relx=0.042, rely=0.211, height=21, width=103
                , bordermode='ignore')
        self.Number_Of_Style_Label.configure(activebackground="#f9f9f9")
        self.Number_Of_Style_Label.configure(activeforeground="black")
        self.Number_Of_Style_Label.configure(background="#d9d9d9")
        self.Number_Of_Style_Label.configure(disabledforeground="#a3a3a3")
        self.Number_Of_Style_Label.configure(foreground="#000000")
        self.Number_Of_Style_Label.configure(highlightbackground="#d9d9d9")
        self.Number_Of_Style_Label.configure(highlightcolor="black")
        self.Number_Of_Style_Label.configure(text='''Number of Styles:''')

        self.Max_Docs_In_Style_Label = tk.Label(self.Result_Labelframe)
        self.Max_Docs_In_Style_Label.place(relx=0.021, rely=0.421, height=21, width=112
                , bordermode='ignore')
        self.Max_Docs_In_Style_Label.configure(activebackground="#f9f9f9")
        self.Max_Docs_In_Style_Label.configure(activeforeground="black")
        self.Max_Docs_In_Style_Label.configure(background="#d9d9d9")
        self.Max_Docs_In_Style_Label.configure(disabledforeground="#a3a3a3")
        self.Max_Docs_In_Style_Label.configure(foreground="#000000")
        self.Max_Docs_In_Style_Label.configure(highlightbackground="#d9d9d9")
        self.Max_Docs_In_Style_Label.configure(highlightcolor="black")
        self.Max_Docs_In_Style_Label.configure(text='''Max Docs In Style:''')

        self.Min_Docs_In_Style_Label = tk.Label(self.Result_Labelframe)
        self.Min_Docs_In_Style_Label.place(relx=0.063, rely=0.632, height=21, width=102
                , bordermode='ignore')
        self.Min_Docs_In_Style_Label.configure(activebackground="#f9f9f9")
        self.Min_Docs_In_Style_Label.configure(activeforeground="black")
        self.Min_Docs_In_Style_Label.configure(background="#d9d9d9")
        self.Min_Docs_In_Style_Label.configure(disabledforeground="#a3a3a3")
        self.Min_Docs_In_Style_Label.configure(foreground="#000000")
        self.Min_Docs_In_Style_Label.configure(highlightbackground="#d9d9d9")
        self.Min_Docs_In_Style_Label.configure(highlightcolor="black")
        self.Min_Docs_In_Style_Label.configure(text='''Min Docs In Style:''')

        self.Number_Of_Style_Result_Label = tk.Label(self.Result_Labelframe)
        self.Number_Of_Style_Result_Label.place(relx=0.542, rely=0.211, height=21, width=54
                , bordermode='ignore')
        self.Number_Of_Style_Result_Label.configure(activebackground="#f9f9f9")
        self.Number_Of_Style_Result_Label.configure(activeforeground="black")
        self.Number_Of_Style_Result_Label.configure(background="#d9d9d9")
        self.Number_Of_Style_Result_Label.configure(disabledforeground="#a3a3a3")
        self.Number_Of_Style_Result_Label.configure(foreground="#000000")
        self.Number_Of_Style_Result_Label.configure(highlightbackground="#d9d9d9")
        self.Number_Of_Style_Result_Label.configure(highlightcolor="black")
        self.Number_Of_Style_Result_Label.configure(text='''5''')

        self.Max_Docs_In_Style_Result_Label = tk.Label(self.Result_Labelframe)
        self.Max_Docs_In_Style_Result_Label.place(relx=0.542, rely=0.421, height=21, width=54
                , bordermode='ignore')
        self.Max_Docs_In_Style_Result_Label.configure(activebackground="#f9f9f9")
        self.Max_Docs_In_Style_Result_Label.configure(activeforeground="black")
        self.Max_Docs_In_Style_Result_Label.configure(background="#d9d9d9")
        self.Max_Docs_In_Style_Result_Label.configure(disabledforeground="#a3a3a3")
        self.Max_Docs_In_Style_Result_Label.configure(foreground="#000000")
        self.Max_Docs_In_Style_Result_Label.configure(highlightbackground="#d9d9d9")
        self.Max_Docs_In_Style_Result_Label.configure(highlightcolor="black")
        self.Max_Docs_In_Style_Result_Label.configure(text='''7''')

        self.Min_Docs_In_Style_Result_Label = tk.Label(self.Result_Labelframe)
        self.Min_Docs_In_Style_Result_Label.place(relx=0.542, rely=0.632, height=21, width=54
                , bordermode='ignore')
        self.Min_Docs_In_Style_Result_Label.configure(activebackground="#f9f9f9")
        self.Min_Docs_In_Style_Result_Label.configure(activeforeground="black")
        self.Min_Docs_In_Style_Result_Label.configure(background="#d9d9d9")
        self.Min_Docs_In_Style_Result_Label.configure(disabledforeground="#a3a3a3")
        self.Min_Docs_In_Style_Result_Label.configure(foreground="#000000")
        self.Min_Docs_In_Style_Result_Label.configure(highlightbackground="#d9d9d9")
        self.Min_Docs_In_Style_Result_Label.configure(highlightcolor="black")
        self.Min_Docs_In_Style_Result_Label.configure(text='''2''')

        self.CopyRight_Label = tk.Label(top)
        self.CopyRight_Label.place(relx=0.422, rely=0.938, height=21, width=87)
        self.CopyRight_Label.configure(activebackground="#f9f9f9")
        self.CopyRight_Label.configure(activeforeground="black")
        self.CopyRight_Label.configure(background="#d9d9d9")
        self.CopyRight_Label.configure(disabledforeground="#a3a3a3")
        self.CopyRight_Label.configure(foreground="#000000")
        self.CopyRight_Label.configure(highlightbackground="#d9d9d9")
        self.CopyRight_Label.configure(highlightcolor="black")
        self.CopyRight_Label.configure(text='''Copyright© RK''')

        self.V_STAGES = {1: self.set_v_get_texts,
                         2: self.set_v_word2vec,
                         3: self.set_v_building_chunks,
                         4: self.set_v_metric,
                         5: self.set_v_pam,
                         6: self.set_v_silhouette}

        self.X_STAGES = {1: self.set_x_get_texts,
                       2: self.set_x_word2vec,
                       3: self.set_x_building_chunks,
                       4: self.set_x_metric,
                       5: self.set_x_pam,
                       6: self.set_x_silhouette}


    def add_word_embedding_checkbox(self, event=None):
        set = self.add_word_emedding_Cbutton_var.get()
        if (set):
            self.load_vec_button.configure(state="active")
            self.vec_entry.configure(state="normal")
        else:
            self.load_vec_button.configure(state="disable")
            self.vec_entry.delete(0,tk.END)
            self.vec_entry.insert(0,"")
            self.vec_entry.configure(state="disable")

    def load_text_button_dialog(self, event=None):
        self.doc_paths = askopenfilenames(title='Choose a text files', filetypes=[("TEXT Files", ".txt")])
        self.num_of_files = root.tk.splitlist(self.doc_paths)  # Possible workaround
        if (len(self.num_of_files) < 3):
            messagebox.showerror("Error selected files", "You must select at least 3 files")
            return
        self.texts_entry.insert(0, self.doc_paths)
        self.to_var.set(len(self.num_of_files)-1) # set maximum possible value
        self.from_var.set(2)
        self.from_spinbox.configure(state="normal")
        self.to_spinbox.configure(state="normal")


    def load_vec_button_dialog(self, event=None):
        vec_path = askopenfilename(title='Choose a vec file', filetypes=[("VEC Files", ".vec")])
        self.vec_entry.insert(0, vec_path)

    def set_from_val(self, event=None):
        if(int(self.to_spinbox.get()) < int(self.from_spinbox.get())):
            self.from_spinbox.invoke("buttondown")

    def set_to_val(self, event=None):
        if(int(self.to_spinbox.get()) < int(self.from_spinbox.get())):
            self.to_spinbox.invoke("buttonup")
        if (int(self.to_spinbox.get()) > int(len(self.num_of_files))-1):
            self.to_spinbox.invoke("buttondown")

    def set_number_of_words_val(self, event=None):
        if(int(self.Number_Of_Words_Spinbox.get()) < 2*int(self.Chunk_Size_Spinbox.get())):
            self.Number_Of_Words_Spinbox.invoke("buttonup")

    def set_chunk_size_val(self, event=None):
        if (int(self.Number_Of_Words_Spinbox.get()) < 2 * int(self.Chunk_Size_Spinbox.get())):
            self.Chunk_Size_Spinbox.invoke("buttondown")
        if (int(self.Delay_Spinbox.get()) == int(self.Chunk_Size_Spinbox.get())):
            self.Chunk_Size_Spinbox.invoke("buttonup")

    def set_delay_val(self, event=None):
        if (int(self.Delay_Spinbox.get()) == int(self.Chunk_Size_Spinbox.get())):
            self.Delay_Spinbox.invoke("buttondown")

    def enable_button_handler(self, event=None):
        set = self.Enable_Cbutton_var.get()
        if (set):
            self.Number_Of_Words_Spinbox.configure(state='normal')
            self.Delay_Spinbox.configure(state='normal')
            self.Chunk_Size_Spinbox.configure(state='normal')
            self.Context_Windows_Spinbox.configure(state='normal')
            self.Softmax_Radiobutton.configure(state="normal")
            self.Negative_Sampling_Radiobutton.configure(state="normal")
            self.CBOW_Radiobutton.configure(state="normal")
            self.Skip_Gram_Radiobutton.configure(state="normal")
            self.Delimiter_window.configure(state="normal")
        else:
            self.Number_Of_Words_Spinbox.configure(state='disable')
            self.Delay_Spinbox.configure(state='disable')
            self.Chunk_Size_Spinbox.configure(state='disable')
            self.Context_Windows_Spinbox.configure(state='disable')
            self.Softmax_Radiobutton.configure(state="disable")
            self.Negative_Sampling_Radiobutton.configure(state="disable")
            self.CBOW_Radiobutton.configure(state="disable")
            self.Skip_Gram_Radiobutton.configure(state="disable")
            self.Delimiter_window.configure(state="disable")

    def set_v_stage(self, stage, event=None):
        self.V_STAGES[stage]()

    def set_x_stage(self, stage, event=None):
        self.X_STAGES[stage]()

    def set_v_get_texts(self, event=None):
        self.v_get_texts_label.place(relx=0.018, rely=0.01)
        self.Processing_TProgressbar['value'] = 16

    def set_x_get_texts(self, event=None):
        self.x_get_texts_label.place(relx=0.018, rely=0.01)

    def set_v_word2vec(self, event=None):
        self.v_word2vec_label.place(relx=0.018, rely=0.12)
        self.Processing_TProgressbar['value'] += 20

    def set_x_word2vec(self, event=None):
        self.x_word2vec_label.place(relx=0.018, rely=0.12)

    def set_v_building_chunks(self, event=None):
        self.v_building_chunks_label.place(relx=0.018, rely=0.23)
        self.Processing_TProgressbar['value'] += 16

    def set_x_building_chunks(self, event=None):
        self.x_building_chunks_label.place(relx=0.018, rely=0.23)

    def set_v_metric(self, event=None):
        self.v_metric_label.place(relx=0.018, rely=0.34)
        self.Processing_TProgressbar['value'] += 16

    def set_x_metric(self, event=None):
        self.x_metric_label.place(relx=0.018, rely=0.34)

    def set_v_pam(self, event=None):
        self.v_pam_label.place(relx=0.018, rely=0.45)
        self.Processing_TProgressbar['value'] += 16

    def set_x_pam(self, event=None):
        self.x_pam_label.place(relx=0.018, rely=0.45)

    def set_v_silhouette(self, event=None):
        self.v_silhouette_label.place(relx=0.018, rely=0.56)
        self.Processing_TProgressbar['value'] += 16

    def set_x_silhouette(self, event=None):
        self.x_silhouette_label.place(relx=0.018, rely=0.56)


    def clean_all_steps(self, event=None):
        self.v_get_texts_label.place_forget()
        self.v_word2vec_label.place_forget()
        self.v_building_chunks_label.place_forget()
        self.v_metric_label.place_forget()
        self.v_pam_label.place_forget()
        self.v_silhouette_label.place_forget()
        self.x_get_texts_label.place_forget()
        self.x_word2vec_label.place_forget()
        self.x_building_chunks_label.place_forget()
        self.x_metric_label.place_forget()
        self.x_pam_label.place_forget()
        self.x_silhouette_label.place_forget()
        self.Processing_TProgressbar['value'] = 0

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="{Segoe UI} 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





